VENDOR: Fix build error implicit declaration of function 'sys_close'
drivers/staging/goldfish/goldfish_sync_timeline.c: In function ‘goldfish_sync_ioctl’:
drivers/staging/goldfish/goldfish_sync_timeline.c:763:4: error: implicit declaration of function ‘sys_close’; did you mean ‘ksys_close’? [-Werror=implicit-function-declaration]
	sys_close(fd_out);

The sys_close has been renamed as ksys_close in commit :
2ca2a09d6215 fs: add ksys_close() wrapper; remove in-kernel calls to sys_close()

Signed-off-by: Pan, Kris <kris.pan@intel.com>