VENDOR : Revert "ANDROID: fiq_debugger: Add option to apply uart overlay by FIQ_DEBUGGER_UART_OVERLAY"
Since v4.17-rc1, the of framework was changed and it need to implement overlay handling in each driver.
Hence we remove it to unblock staging build and will integate it until google refactory it.

drivers/staging/android/fiq_debugger/fiq_debugger.c: In function ?fiq_debugger_uart_overlay?:
drivers/staging/android/fiq_debugger/fiq_debugger.c:1219:2: error: implicit declaration of function ?of_overlay_create? [-Werror=implicit-function-declaration]
  ret = of_overlay_create(onp);
  ^

This reverts commit 7f1b239030955972c0e260645a0a7878b13bf707.

Signed-off-by: Pan, Kris <kris.pan@intel.com>